# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: FRONT CI
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm install 
    - run: npm run build --if-present
      env:
        VUE_APP_FIREBASE_API_KEY: ${{ secrets.firebase_api_key }}
        VUE_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.firebase_auth_domain }}
        VUE_APP_FIREBASE_AUTH_DATABASE_URL: ${{ secrets.firebase_database_url }}
        VUE_APP_FIREBASE_PROJECT_ID: ${{ secrets.firebase_project_id }} 
        VUE_APP_FIREBASE_STORAGE_BUCKET: ${{ secrets.firebase_storage_bucket }} 
        VUE_APP_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.firebase_sender_id }} 
        VUE_APP_FIREBASE_APP_ID: ${{ secrets.firebase_app_id }} 
        VUE_APP_FIREBASE_MEASUREMENT_ID: ${{ secrets.firebase_measurement_id }} 
        VUE_APP_API_ENDPOINTS: ${{ secrets.api_endpoints }}
    - name: Firebase GitHub Action
      uses: pizzafox/firebase-action@1.0.7
      env:
        PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      with:
        args: deploy
